nelmio_api_doc:
    documentation:
        info:
            title: Bands Service - API Documentation
            description: Swagger documentation for the Bands Service API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/ # Accepts routes under /api except /api/doc
        name_patterns:
            - ^app_  # Include only routes starting with api_
        host_patterns: [ ]