services:
  app:
    container_name: bands-service-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      CORS_ALLOW_ORIGIN: "*"
    depends_on:
      - database
    networks:
      - symfony

  nginx:
    container_name: bands-service-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '8078:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  database:
    container_name: bands-service-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bands-service
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4309:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: bands-service-swagger-ui
    restart: unless-stopped
    ports:
      - "8079:8080"
    depends_on:
      - nginx
    environment:
      SWAGGER_JSON_URL: "${SWAGGER_JSON_URL}"
    networks:
      - symfony
networks:
  symfony:
    driver: bridge

volumes:
  mysql_data: